#!/bin/bash

case "$2" in
  up)
    ssid=$(nmcli -g TYPE,NAME connection show --active | grep -oE '802-11-wireless:(WIFIonICE|DBLounge)')
    if [[ $ssid ]]; then
      python3 /usr/share/db_wlan_manager/manager.py -b $ssid 2>&1 >> /var/log/dbwifi
    fi
    ;;
  down)
    # Nothing to do: nm will kill all it's child processes when the iface does down.
    ;;
esac
